### PR TITLE
Created Customized Format Downloadable QR

### LINKED ISSUE #24: Make QR Downloadable In Different Formats
**Description-**
Currently, the QR is Downloading in PNG format only
Make QR Downloadable In Different Formats, for example - JPG, PDF, etc.. as per what user chooses

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #24

**Screenshot/Video-**

https://github.com/1010varun/qr-convertor/assets/140608790/72f67ca6-8d53-45ba-ba25-0b2baa64709f

### CODE REVIEW

**Comment by 1010varun** [comment]
@JiyaGupta-cs can you also add PDF format in the option

**Comment by JiyaGupta-cs** [comment]
@1010varun PDF Format requires other plugins to convert png or jpg to pdf
React file saver which is used earlier can't do that

**Comment by JiyaGupta-cs** [comment]
@1010varun Please review the PR

**Comment by 1010varun** [comment]
lgtm

**Pull request merged**
