### PR TITLE
Made Footer Attractive

### LINKED ISSUE #10: [FEAT]: Enhanced Footer
The current footer looks like this

image

I want to create a beautiful footer with animations in it which would make the website look attractive.

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Fixes #10 
Made the footer attractive by adding waves animation to it

https://github.com/1010varun/qr-convertor/assets/140608790/d68e7537-99be-4cd3-a335-7724cd5ce70e

### CODE REVIEW

**Comment by 1010varun** [comment]
image
image

@JiyaGupta-cs make it responsive

**Comment by JiyaGupta-cs** [comment]
It's already responsive sir

**Comment by 1010varun** [comment]
It's not see in the above image it is below the visible screen and in mobile view, most of the space is empty after the footer it should stick to the bottom of screen

**Comment by JiyaGupta-cs** [comment]
image
image

It's working now 
I have fixed it

**Comment by JiyaGupta-cs** [comment]
@1010varun Can you please check the updated code
I have tested it on my local system
It's working fine now

**Comment by 1010varun** [comment]
image
corrected in mobile version but not in desktop one

**Comment by JiyaGupta-cs** [comment]
@1010varun Fixed in desktop mode also

**Comment by 1010varun** [comment]
@JiyaGupta-cs, seems good to me, thanks for the patch

**Pull request merged**
