### PR TITLE
feat: PR Title Checker

### LINKED ISSUE #43: [Feature] Adding PR TITLE CHECK WORKFLOW FOR GITHUB
### Describe the feature you'd like to request

Please assign me this issue under IWOC

### Describe the solution you'd like

Implementing it would allow automation

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #43

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@1010varun Please review the PR

**Comment by 1010varun** [comment]
@JiyaGupta-cs add more prefixes to the file

**Comment by JiyaGupta-cs** [comment]
@1010varun Please elaborate what prefixes ?

**Comment by JiyaGupta-cs** [comment]
@1010varun I have updated , Please check

**Comment by JiyaGupta-cs** [comment]
@1010varun Please review the PR

**Pull request merged**
